# NumPy

In [ ]:
NumPy >> Numerical Python
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.


In [ ]:
Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with 
ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
import numpy
import numpy as np

#### Applications

In [ ]:
1. Linear Algebra
2. Statistics
3. Trigonometry
4. Matrix Operations
5. Image Processing
6. Logarithmic Operations

#### Properties

In [ ]:
1. It is a collection of homogenous Datatypes.
2. Numpy array is faster than list(heterogenous)
3. Numpy is writtedn in C and C++ Language (Partially in Python)
4. C Language is faster than Python
5. ndarray >> n dimensional array (0D,1D,2D,3D,nD)
6. Array can be created using list or tuple

In [2]:
lst = [1,2,3,4,5]
type(lst)

list

### 1. np.array()

In [3]:
arr1 = np.array(1,2,3,4,5)
arr1

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [4]:
arr1 = np.array([1,2,3,4,5])   # list
arr1

array([1, 2, 3, 4, 5])

In [6]:
tup = np.array((1,2,3,4,5,6))    # tuple
tup

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
type(tup)

numpy.ndarray

In [9]:
# Zero dimensional array

arr1 = np.array(100)
arr1

array(100)

In [10]:
list1 = [1,2,3,4,5]
arr = np.array(l1)
arr

array([1, 2, 3, 4, 5])

In [11]:
list1 = [1,2,3,4,5]
arr = np.array(l1)
print(arr)

[1 2 3 4 5]


In [12]:
l2 = [[1,2],[3,4]]
l2

[[1, 2], [3, 4]]

In [13]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [14]:
print(arr)

[[1 2]
 [3 4]]


### Type casting in NumPy Array

In [ ]:
int >> float
int >> complex
int >> str/objec

In [15]:
l1 = [1,2,3,4,5,5.5]
l1

[1, 2, 3, 4, 5, 5.5]

In [16]:
array = np.array([1,2,3,4,5,5.5])
array

array([1. , 2. , 3. , 4. , 5. , 5.5])

In [17]:
print(array)

[1.  2.  3.  4.  5.  5.5]


In [18]:
array = np.array([1,2,3,4,5,5.5], dtype = int)
array

array([1, 2, 3, 4, 5, 5])

In [19]:
array = np.array([1,2,3,4,5,5.5], dtype = 'int')
array

array([1, 2, 3, 4, 5, 5])

In [20]:
array = np.array([1,2,3,4,5,5.5], dtype = int)
array

array([1, 2, 3, 4, 5, 5], dtype=int32)

In [ ]:
array = np.array([1,2,3,4,5,5.5], int)
array

In [24]:
array = np.array([1,2,3,4,5,5.5])
array

array([1. , 2. , 3. , 4. , 5. , 5.5])

In [25]:
array = np.array([1,2,3,4,5,5])
array

array([1, 2, 3, 4, 5, 5])

In [21]:
array = np.array([1,2,3,4,5,5.5], dtype = float)
array

array([1. , 2. , 3. , 4. , 5. , 5.5])

In [22]:
array = np.array([1,2,3,4,5,5.5], dtype = 'float')
array

array([1. , 2. , 3. , 4. , 5. , 5.5])

In [23]:
array = np.array([1,2,3,4,5,5.5], dtype = 'f')
array

array([1. , 2. , 3. , 4. , 5. , 5.5], dtype=float32)

In [26]:
array = np.array([1,2,3,4,5,5.5], dtype = complex)
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 5.5+0.j])

In [27]:
array = np.array([1,2,3,4,5,5.5], dtype = 'complex')
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 5.5+0.j])

In [28]:
array = np.array([1,2,3,4,5,5.5], dtype = str)
array

array(['1', '2', '3', '4', '5', '5.5'], dtype='<U3')

In [30]:
array = np.array([1,2,3,4,5,5], dtype = 'str')
array

array(['1', '2', '3', '4', '5', '5'], dtype='<U1')

In [31]:
array = np.array([1,2,3,4,5,5.5], dtype = object)
array

array([1, 2, 3, 4, 5, 5.5], dtype=object)

In [ ]:
str is equivalent to object

### Float to other Datatype

In [32]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48])
array

array([3.  , 4.1 , 5.5 , 6.  , 7.  , 5.48])

In [33]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48], float)
array

array([3.  , 4.1 , 5.5 , 6.  , 7.  , 5.48])

In [40]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48, 0.1], int)
array

array([3, 4, 5, 6, 7, 5, 0])

In [42]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48], 'int')
array

array([3, 4, 5, 6, 7, 5])

In [35]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48], 'complex')
array

array([3.  +0.j, 4.1 +0.j, 5.5 +0.j, 6.  +0.j, 7.  +0.j, 5.48+0.j])

In [36]:
array = np.array([3, 4.1, 5.5, 6, 7, 5.48], 'str')
array

array(['3', '4.1', '5.5', '6', '7', '5.48'], dtype='<U4')

### Complex to other datatypes

In [ ]:
We cannot convert complex to int.

In [43]:
array1 = np.array([2+3j, 10,20,30,40])
array1           # all values converted into complex

array([ 2.+3.j, 10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j])

In [44]:
array1 = np.array([2+3j, 10,20,30,40], int)
array1           # complex cannot converted into int

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [45]:
array1 = np.array([2+3j, 10,20,30,40], float)
array1          # complex cannot converted into float

TypeError: float() argument must be a string or a real number, not 'complex'

In [46]:
array1 = np.array([2+3j, 10,20,30,40], str)
array1                       # can be converted into string

array(['(2+3j)', '10', '20', '30', '40'], dtype='<U6')

### Numerical Operations

In [47]:
arr2 = np.array([3,4,5,6,7])
arr2

array([3, 4, 5, 6, 7])

In [48]:
list_1 = [1,2,3,4,5]
sqr_list = [i**2 for i in list_1]
sqr_list

[1, 4, 9, 16, 25]

In [49]:
list_1 = [1,2,3,4,5]
add_10 = [i+10 for i in list_1]
add_10

[11, 12, 13, 14, 15]

In [50]:
arr = np.array([1,2,3,4,5])
arr**2                       # directly operation is done on variable

array([ 1,  4,  9, 16, 25])

In [51]:
arr = np.array([1,2,3,4,5])
arr+10                       # directly operation is done on variable

array([11, 12, 13, 14, 15])

In [ ]:
arr = np.array([1,2,3,4,5])
arr*10                       # directly operation is done on variable

In [52]:
arr = np.array([1,2,3,4,5])
arr/2                       # directly operation is done on variable

array([0.5, 1. , 1.5, 2. , 2.5])

In [54]:
arr = np.array([1,2,3,4,5])
arr//2                       # directly operation is done on variable

array([0, 1, 1, 2, 2], dtype=int32)

In [55]:
arr = np.array([1,2,3,4,5])
arr%2                       # directly operation is done on variable

array([1, 0, 1, 0, 1], dtype=int32)

In [56]:
arr = np.array([1,2,3,4,5])
arr-2                       # directly operation is done on variable

array([-1,  0,  1,  2,  3])

In [57]:
list1 = [2,3,4,5,8,9]
cubes = np.array(list1) ** 3
cubes

array([  8,  27,  64, 125, 512, 729], dtype=int32)

In [58]:
list1 = [2,3,4,5,8,9]
cubes = np.array(list1) ** 3
cubes.tolist()

[8, 27, 64, 125, 512, 729]

In [59]:
list1 = [2,3,4,5,8,9]
cubes = np.array(list1) ** 3
list(cubes)

[8, 27, 64, 125, 512, 729]

In [60]:
list1 = [2,3,4,5,8,9]
cubes = (np.array(list1) ** 3).tolist()
cubes

[8, 27, 64, 125, 512, 729]

In [61]:
arr = np.array([1,2,3,4,5])
arr-5                     # directly operation is done on variable

array([-4, -3, -2, -1,  0])

In [62]:
arr = np.array([1,2,3,4,5.5])
arr-5                     # directly operation is done on variable

array([-4. , -3. , -2. , -1. ,  0.5])

In [64]:
arr = np.array([1,2,3,'4',5.5])
arr                    # directly operation is done on variable

array(['1', '2', '3', '4', '5.5'], dtype='<U32')

In [65]:
arr = np.array([1,2,3,'4',5.5])
arr - 5                   # directly operation is done on variable

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

In [66]:
arr = np.array([1,2,3,'4',5.5])
arr*2                    # directly operation is done on variable

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

In [68]:
'4' * 2           # single item  working as a string, array consist of multiple types of elements

'44'

### Dimensions in Array

#### 1.  Zero Dimensional Array

In [ ]:
Zero dimensional  >> array containing only one value

In [69]:
arr0 = np.array(10)
arr0

array(10)

In [71]:
arr0 = np.array(10)     # zero square bracket >> zero dimensional
print("Number of dimensions are : " ,arr0.ndim)

Number of dimensions are :  0


In [73]:
arr0 = np.array((10))        # one square bracket >> one dimensional   >> tuple
print("Number of dimensions are : " ,arr0.ndim)

Number of dimensions are :  0


In [72]:
arr0 = np.array([10])        # one square bracket >> one dimensional
print("Number of dimensions are : " ,arr0.ndim)

Number of dimensions are :  1


In [ ]:
To get dimensions simply count number of square brackets.

#### 2. One Dimensional Array

In [ ]:
It is a collection of multiple 0D array

In [79]:
arr1 = np.array([4,5,6,7,8,9])
print("Array is:\n", arr1)
print("Number of dimensions : ", arr1.ndim)
print()

Array is:
 [4 5 6 7 8 9]
Number of dimensions :  1



In [80]:
arr1 = np.array([4,5,6,7,8.5,900])
print("Array is:\n", arr1)
print("Number of dimensions : ", arr1.ndim)
print()

Array is:
 [  4.    5.    6.    7.    8.5 900. ]
Number of dimensions :  1



#### 3. Two Dimensional Array

In [ ]:
It is a collection of multiple 1D arrays.>> Nested list

In [81]:
arr2 = np.array([[4,5],[6,7],[8,90]])
print("Array is:\n", arr2)
print("Number of dimensions : ", arr2.ndim)
print()

Array is:
 [[ 4  5]
 [ 6  7]
 [ 8 90]]
Number of dimensions :  2



In [ ]:
Arrays wants things identical.

In [86]:
arr2 = np.array([[4,5,6],[7,8,9],[10,11,12,13]])
print('Array is :\n', arr2)
print('Number of Dimensions are :', arr2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [88]:
arr2 = np.array([[4,5,6,np.nan],[7,8,9, np.nan],[10,11,12,13]])
print('Array is :\n', arr2)
print('Number of Dimensions are :', arr2.ndim)

Array is :
 [[ 4.  5.  6. nan]
 [ 7.  8.  9. nan]
 [10. 11. 12. 13.]]
Number of Dimensions are : 2


In [ ]:
nan >>  not a number

In [89]:
list2 = [[4,5,6],[40,50,60],[44,66,88]]
print(list2)
type(list2)

[[4, 5, 6], [40, 50, 60], [44, 66, 88]]


list

In [96]:
arr2 = np.array([[4,5,6],[40,50,60],[44,66,88]])
arr2

array([[ 4,  5,  6],
       [40, 50, 60],
       [44, 66, 88]])

In [100]:
arr2.ndim

2

In [104]:
arr1 = np.array([1,2,3])    # multiple 0D values
arr1.shape

(3,)

In [105]:
arr1.ndim

1

In [106]:
arr2 = np.array([[4,5,6],[40,50,60],[44,66,88]])
arr2

array([[ 4,  5,  6],
       [40, 50, 60],
       [44, 66, 88]])

In [107]:
arr2.shape  # (1D, 0D)

(3, 3)

In [108]:
arr2 = np.array([[4,5,6,7],[40,50,60,7],[44,66,88,8]])
arr2

array([[ 4,  5,  6,  7],
       [40, 50, 60,  7],
       [44, 66, 88,  8]])

In [110]:
arr2.ndim

2

In [109]:
arr2.shape

(3, 4)

In [111]:
arr2 = np.array([[4,5,6],[40,50,60],[44,66,88],[1,2,3]])
arr2

array([[ 4,  5,  6],
       [40, 50, 60],
       [44, 66, 88],
       [ 1,  2,  3]])

In [112]:
arr2.shape     # gives answer in tuple

(4, 3)

In [114]:
arr2 = np.array([[4,5,6],[40,50,60],[44,66,88],[1,2,3]])
row_count = arr2.shape[0]
col_count = arr2.shape[1]
print("Number of rows : ", row_count)
print("Number of Columns : ", col_count)


Number of rows :  4
Number of Columns :  3


#### 4. Three Dimensional Array

In [ ]:
It is a collection of multiple 2D arrays. 2D >> 1D >> 0D

In [118]:
arr1 = np.array([2,3,4,5,6])    # multiple 0D arrays
print("Array is : \n",arr1)
print("Number of Dimensions :" , arr1.ndim)
print("Shape of Array :" , arr1.shape)

Array is : 
 [2 3 4 5 6]
Number of Dimensions : 1
Shape of Array : (5,)


In [120]:
arr2 = np.array([[2,3,4,5],[6,4,5,6]])    # multiple 1D arrays
print("Array is : \n",arr2)
print("Number of Dimensions :" , arr2.ndim)
print("Shape of Array :" , arr2.shape)

Array is : 
 [[2 3 4 5]
 [6 4 5 6]]
Number of Dimensions : 2
Shape of Array : (2, 4)


In [122]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])    # multiple 2D arrays
print("Array is : \n",arr3)
print("Number of Dimensions :" , arr3.ndim)
print("Shape of Array :" , arr3.shape)

Array is : 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Number of Dimensions : 3
Shape of Array : (1, 3, 3)


In [125]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])    # multiple 2D arrays
print("Array is : \n",arr3)
print("Number of Dimensions :" , arr3.ndim)
print("Shape of Array :" , arr3.shape)

# Number of 0D >> 2
# Number Of 1D >> 2
# Number of 2D >> 2

Array is : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of Dimensions : 3
Shape of Array : (2, 2, 2)


In [127]:
arr3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])    # multiple 2D arrays
print("Array is : \n",arr3)
print("Number of Dimensions :" , arr3.ndim)
print("Shape of Array :" , arr3.shape)

# Number of 0D >> 2
# Number Of 1D >> 4
# Number of 2D >> 1

Array is : 
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
Number of Dimensions : 3
Shape of Array : (1, 4, 2)


In [128]:
arr3 = np.array([[[1,2],[3,4],[8,9]],[[5,6],[7,8],[8,6]]])    # multiple 2D arrays
print("Array is : \n",arr3)
print("Number of Dimensions :" , arr3.ndim)
print("Shape of Array :" , arr3.shape)

# Number of 0D >> 2
# Number Of 1D >> 3
# Number of 2D >> 2

Array is : 
 [[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [8 6]]]
Number of Dimensions : 3
Shape of Array : (2, 3, 2)


In [129]:
arr3 = np.array([[[1,2],[3,4],[8,9]],[[5,6],[7,8],[8,6]]])    # multiple 2D arrays
print("Array is : \n",arr3)
print("Number of Dimensions :" , arr3.ndim)
print("Shape of Array :" , arr3.shape)

# Number of 0D >> 2
# Number Of 1D >> 3
# Number of 2D >> 2

Array is : 
 [[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [8 6]]]
Number of Dimensions : 3
Shape of Array : (2, 3, 2)


In [138]:
arr4 = np.array([[[[1,2],[2,3]],[[2,3],[4,5]]]])  
print('Array is :\n', arr4)
print('Number of Dimensions are :', arr4.ndim)
print('Shape of an array is:', arr4.shape)

# NUmber of 0D >> 2
# NUmber of 1D >> 2
# NUmber of 2D >> 2
# NUmber of 3D >> 1

Array is :
 [[[[1 2]
   [2 3]]

  [[2 3]
   [4 5]]]]
Number of Dimensions are : 4
Shape of an array is: (1, 2, 2, 2)


In [4]:
import numpy as np
arr4 = np.array([[[[1,2],[2,3]],[[2,3],[4,5]]], [[[3,4],[5,6]],[[3,4],[5,6]]]])  
print('Array is :\n', arr4)
print('Number of Dimensions are :', arr4.ndim)
print('Shape of an array is:', arr4.shape)

# NUmber of 0D >> 2
# NUmber of 1D >> 2
# NUmber of 2D >> 2
# NUmber of 3D >> 1

Array is :
 [[[[1 2]
   [2 3]]

  [[2 3]
   [4 5]]]


 [[[3 4]
   [5 6]]

  [[3 4]
   [5 6]]]]
Number of Dimensions are : 4
Shape of an array is: (2, 2, 2, 2)


In [5]:
import numpy as np
arr4 = np.array([[[[1,2],[2,3]],[[2,3],[4,5]],[[3,4],[5,6]],[[3,4],[5,6]]]])  
print('Array is :\n', arr4)
print('Number of Dimensions are :', arr4.ndim)
print('Shape of an array is:', arr4.shape)

# NUmber of 0D >> 2
# NUmber of 1D >> 2
# NUmber of 2D >> 2
# NUmber of 3D >> 1

Array is :
 [[[[1 2]
   [2 3]]

  [[2 3]
   [4 5]]

  [[3 4]
   [5 6]]

  [[3 4]
   [5 6]]]]
Number of Dimensions are : 4
Shape of an array is: (1, 4, 2, 2)


In [ ]:
0D
1D >> 0D
2D >> 1D >> 0D
3D >> 2D >> 1D >> 0D
4D >> 3D >> 2D >> 1D >> 0D

In [7]:
arr0 = np.array(30)
arr0.shape

()

In [8]:
arr1 = np.array([30])
arr1.shape

(1,)

In [9]:
np.array([1,2,5, np.nan])

array([ 1.,  2.,  5., nan])